CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    CURRENCY BIGINT NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    primary key (ACCOUNT_NUMBER)
);
